### ISSUE TITLE
Update recent papers

### ISSUE THREAD

**Issue by 1uciusy** [opendilab/awesome-end-to-end-autonomous-driving#2]
It's been a long time since this repo was updated 6 months ago. ICCV2023 has passed and CVPR2024 is comming, is there a plan that corresponding papers will be updated?

**Comment by TuTuHuss** [comment]
Hi 1uciusy,
We appreciate your keen interest in our warehouse operations. We are pleased to inform you that an update plan for the warehouse is currently in the pipeline and being meticulously scheduled. You will be promptly notified of any developments via our [Discord channel](https://discord.gg/dkZS2JF56X) once the update is implemented.

Additionally, I wanted to take this opportunity to inform you about our ongoing developer recruitment initiative. If you are enthusiastic about contributing to our warehouse through engaging and innovative work, we would be more than willing to assign a task tailored to your expertise and interests. For insights into the types of projects we have previously undertaken, you may refer to `[here](https://github.com/opendilab/DI-engine/issues/621)`.

We look forward to your potential involvement and to the possibility of enriching our team with your valuable skills.

**Comment by TuTuHuss** [comment]
Hi 1uciusy,
We appreciate your keen interest in our warehouse operations. We are pleased to inform you that an update plan for the repository is currently in the pipeline and being meticulously scheduled. You will be promptly notified of any developments via our [Discord channel](https://discord.gg/dkZS2JF56X) once the update is implemented.

Additionally, I wanted to take this opportunity to inform you about our ongoing developer recruitment initiative. If you are enthusiastic about contributing to our warehouse through engaging and innovative work, we would be more than willing to assign a task tailored to your expertise and interests. For insights into the types of projects we have previously undertaken, you may refer to `[here](https://github.com/opendilab/DI-engine/issues/621)`.

We look forward to your potential involvement and to the possibility of enriching our team with your valuable skills.

**Comment by TuTuHuss** [comment]
Hi 1uciusy,
We appreciate your keen interest in our repository operations. We are pleased to inform you that an update plan for the repository is currently in the pipeline and being meticulously scheduled. You will be promptly notified of any developments via our [Discord channel](https://discord.gg/dkZS2JF56X) once the update is implemented.

Additionally, I wanted to take this opportunity to inform you about our ongoing developer recruitment initiative. If you are enthusiastic about contributing to our warehouse through engaging and innovative work, we would be more than willing to assign a task tailored to your expertise and interests. For insights into the types of projects we have previously undertaken, you may refer to [here](https://github.com/opendilab/DI-engine/issues/621).

We look forward to your potential involvement and to the possibility of enriching our team with your valuable skills.

**Comment by 1uciusy** [comment]
Thank you for your invitation, but i'm graduating and Autonomous Driving is not my future working area. I will share this information to my classmates in my lab.
